version: '3'

services:
  haproxy:
    image: haproxy:1.8.14-alpine
    #image: haproxy
    ports:
      - 80:80
      - 81:81
      - 82:82
      - 83:83
      - 84:84
      - 85:85
      - 1936:1936
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    deploy:
      mode: global

  web1:
    image: nginx
    volumes:
      - ./web1/nginxlogs:/var/log/nginx/
      - ./web1/nginx.conf:/etc/nginx/nginx.conf
      - ./web1/html:/usr/share/nginx/html
      - ./web1/static:/usr/share/nginx/static/

  web2:
    image: nginx
    volumes:
      - ./web2/nginxlogs:/var/log/nginx/
      - ./web2/nginx.conf:/etc/nginx/nginx.conf
      - ./web2/html:/usr/share/nginx/html
      - ./web2/static:/usr/share/nginx/static/
